apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres-trading
    type: postgres
    access: proxy
    url: postgres:5432
    database: trading
    user: trading
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: trading
